language: python

python:
  - "2.7"

addons:
  apt:
    packages:
    - gcc
    - gfortran
    - libblas-dev
    - liblapack-dev


os:
  - linux

branches:
  only:
    - master
    - /^test-.*$/

install: "python setup.py install"

script: nosetests