language: python

python:
  - "2.7"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - libatlas-dev
    - liblapack-dev
    - libatlas-base-dev
    - gfortran

os:
  - linux

branches:
  only:
    - master
    - /^test-.*$/

install:
  - "pip install -r requirements.txt"
  - "python setup.py install"

script: nosetests